# Generated by Django 5.0.3 on 2024-03-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_department_remove_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_patients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('am', 'AM'), ('pm', 'PM')], default='am', max_length=10),
        ),
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='health.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='health.patient')),
            ],
        ),
    ]
