# Generated by Django 5.0.3 on 2024-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_remove_patient_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identify_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
