# Generated by Django 5.0.3 on 2024-04-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_patient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(default='patient', max_length=20),
        ),
    ]
