# Generated by Django 5.0.3 on 2024-04-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_patient_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='role',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
