# Generated by Django 5.0.3 on 2024-04-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_remove_patient_role_patient_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(default='unallocated', max_length=50),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='extra_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(default='undefined', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='identify_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
