# Generated by Django 5.0.3 on 2024-04-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
