# Generated by Django 5.0.3 on 2024-04-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_remove_patientappointment_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
