# Generated by Django 5.0.3 on 2024-05-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_alter_schedule_doctor_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(default='Highfield', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending Confirmation', max_length=50),
        ),
    ]
