# Generated by Django 5.0.3 on 2024-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0020_appointment_appointment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
