# Generated by Django 5.0.3 on 2024-05-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0021_medicalrecord_appointment_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='created_at',
            new_name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
