# Generated by Django 5.0.3 on 2024-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0022_rename_created_at_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_advice',
            field=models.TextField(blank=True, default="Please be patient and wait for the doctor's answer", null=True),
        ),
    ]
