# Generated by Django 5.0.3 on 2024-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0023_alter_appointment_doctor_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis_description',
            field=models.TextField(blank=True, default="Please be patient and wait for the doctor's answer", null=True),
        ),
    ]
